### ISSUE TITLE
module don't update

### ISSUE THREAD

**Issue by andre0183** [magenta-aps/ldap-multi-search-base#1]
Hello, 

I have installed the module and when I tried to add a new chain of ldap, the configuration don't take new changes. Why is this happening?

I appreciate your help.

**Comment by syastrov** [comment]
What do you mean add a new chain?
Can you paste your alfresco-global.properties?
What version of Alfresco are you using?

**Comment by andre0183** [comment]
Hi Seth,

I have alfresco community 5.0.0d, my configuration is the next:

authentication.chain=alfrescoNtlm1:alfrescoNtlm, ldap1:ldap

ldap.synchronization.groupSearchBase=ou=Active,ou=Users,ou=p1,dc=mycompany,dc=com:ou=Users,ou=p2,dc=mycompany,dc=com:ou=p3,dc=mycompany,dc=com:ou=p4,dc=mycompany,dc=com:ou=ce,ou=p5,dc=mycompany,dc=com

When I try to add this two additional chanins, the new configuration don`t
works, don't synchronizes the new users at this OU's:

ou=Users,ou=ws,ou=c1,ou=p5,dc=mycompany,dc=com:ou=ceg,ou=c2,ou=p5,dc=mycompany,dc=com

Can you give me a clue? How can update the configuration with this module
installed?

Thanks for your reply

2016-03-01 9:56 GMT-05:00 Seth Yastrov notifications@github.com:

**Comment by syastrov** [comment]
It has not been tested on Alfresco 5.0.d, only on Alfresco 5.0.c. I believe there were only minor changes in 5.0.d, however, so it probably should still work.

There should be no space in authentication.chain value:
`authentication.chain=alfrescoNtlm1:alfrescoNtlm,ldap1:ldap`

The = should be escaped as \=, for example:
`ldap.synchronization.groupSearchBase=ou\=Active,ou\=Users,ou\=p1,dc\=mycompany....`

Can you add this line to log4j.properties to turn on debug information:
`log4j.logger.dk.magenta.ldap.LDAPMultiBaseUserRegistry=DEBUG`

Make sure you are also doing a full sync (synchronization.synchronizeChangesOnly=false) as well.
You can look at an example configuration to see if anything else looks wrong: https://github.com/magenta-aps/ldap-multi-search-base/blob/master/src/test/properties/local/alfresco-global.properties

After you run it again, can you post the output of alfresco.log?

**Comment by andre0183** [comment]
Hi Seth,

Thanks a lot, I have applied the configuration that you said and it works
fine in Alfresco 5.
It was worth it the observation. :)

2016-03-01 10:25 GMT-05:00 Seth Yastrov notifications@github.com:
